FROM node:14.17.6
LABEL maintainer="ezTEAM <ezpaarse@couperin.org>"

RUN useradd -rm -d /home/kbn-dev -s /bin/bash -u 8854 kbn-dev \
  && chown -R kbn-dev /usr/local

USER kbn-dev

WORKDIR /home/kbn-dev

RUN git clone --progress --verbose https://github.com/elastic/kibana \
  && cd ./kibana \
  && git checkout 7.14 \
  && yarn kbn bootstrap

EXPOSE 5601
EXPOSE 5603

CMD [ "yarn", "start" ]