services:
  # We use dex as default authentication provider, you can choose another one that fits your needs,
  # as longs as it provides OIDC authentication
  dex:
    image: 'dexidp/dex:v2.45.1-alpine'
    restart: "no"
    env_file:
      - path: ${PWD}/.env
        required: true
      - path: ${PWD}/.env.local
        required: false
    environment:
      EZMESURE_OIDC_ISSUER_URI: https://${EZMESURE_DOMAIN}/auth
      # echo changeme | htpasswd -BinC 10 admin | cut -d: -f2
      EZMESURE_ADMIN_PASSWORD_HASH: "$2y$10$/Ctv48gjpa9DbcRB3djGQOujxIoUCfxrfFlwYKtW4k6D6.SgC6OP."
    volumes:
      - ${PWD}/docker/dex/dex.yaml:/etc/dex/config.docker.yaml
      - ${PWD}/docker/certs/ca.pem:/etc/ssl/ezmesure.pem:ro
