#!/bin/bash
set -e

if [[ ! -v APPLI_APACHE_SERVERNAME ]]; then
  echo "Missing env: APPLI_APACHE_SERVERNAME"
  exit 1
fi
if [[ ! -v APPLI_APACHE_SERVERADMIN ]]; then
  echo "Missing env: APPLI_APACHE_SERVERADMIN"
  exit 1
fi
if [[ ! -v APPLI_APACHE_LOGLEVEL ]]; then
  echo "Missing env: APPLI_APACHE_LOGLEVEL"
  exit 1
fi

/etc/init.d/shibd start

# Apache gets grumpy about pre-existing PID files
rm -f /var/run/apache2/apache2.pid

exec apachectl -DFOREGROUND
