#!/bin/bash
set -e

if [[ ! -v APPLI_APACHE_SERVERNAME ]]; then
  echo "Missing env: APPLI_APACHE_SERVERNAME"
  exit 1
fi
if [[ ! -v APPLI_APACHE_SERVERADMIN ]]; then
  echo "Missing env: APPLI_APACHE_SERVERADMIN"
  exit 1
fi
if [[ ! -v APPLI_APACHE_LOGLEVEL ]]; then
  echo "Missing env: APPLI_APACHE_LOGLEVEL"
  exit 1
fi

if [[ $container == "podman" ]]; then
  echo "==== podman does not support chown ===="
  echo "To allow shibboleth to write in a mounted volume, please use:"
  SHIBD_USERID=$(id -u _shibd)
  SHIBD_GROUPID=$(id -g _shibd)
  echo "- chown -R $SHIBD_USERID:$SHIBD_GROUPID <volume of /var/cache/shibboleth>"
  echo "- chown -R $SHIBD_USERID:$SHIBD_GROUPID <volume of /var/log/shibboleth>"
  echo ""
  echo "Example with default configuration:"
  echo "  chown -R $SHIBD_USERID:$SHIBD_GROUPID rp/sp-{cache,log}"
  echo "========"
else
  # Allow shibboleth to write in a mounted volume
  chown -R _shibd:_shibd /var/cache/shibboleth
fi

if [[ -z "$EZMESURE_DISABLE_SHIBBOLETH" ]]; then
  if [[ ! -v SHIBBOLETH_SP_URL ]]; then
    echo "Missing env: SHIBBOLETH_SP_URL"
    exit 1
  fi
  if [[ ! -v SHIBBOLETH_DS_URL ]]; then
    echo "Missing env: SHIBBOLETH_DS_URL"
    exit 1
  fi

  # patch shibboleth2.xml config file with SP/DS URLs
  sed -e "s|{{SHIBBOLETH_SP_URL}}|${SHIBBOLETH_SP_URL}|" \
      -e "s|{{SHIBBOLETH_DS_URL}}|${SHIBBOLETH_DS_URL}|" \
      /etc/shibboleth/shibboleth2.dist.xml > /etc/shibboleth/shibboleth2.xml

  a2enmod shib
  a2enconf shib
  a2ensite default-ssl
  a2dissite default-ssl-no-shib
  /etc/init.d/shibd start
else
  a2dismod shib
  a2disconf shib
  a2ensite default-ssl-no-shib
  a2dissite default-ssl
fi

# Apache gets grumpy about pre-existing PID files
rm -f /var/run/apache2/apache2.pid

exec apachectl -DFOREGROUND
