issuer: {{ getenv "EZMESURE_OIDC_ISSUER_URI" }}

storage:
  type: sqlite3
  config:
    file: "/var/dex/dex.db"

web:
  http: "0.0.0.0:5556"

expiry:
  deviceRequests: "5m"
  signingKeys: "6h"
  idTokens: "24h"
  authRequests: "24h"

logger:
  level: info
  format: text

enablePasswordDB: true

staticPasswords:
  - email: {{ getenv "EZMESURE_ADMIN_EMAIL" "ezmesure-admin@admin.com" }}
    hash: {{ getenv "EZMESURE_ADMIN_PASSWORD_HASH" }}
    username: {{ getenv "EZMESURE_ADMIN_USERNAME" "ezmesure-admin" }}
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

oauth2:
  responseTypes: [code]
  skipApprovalScreen: false
  alwaysShowLoginScreen: false

staticClients:
- id: {{ getenv "EZMESURE_OIDC_CLIENT_ID" }}
  secret: {{ getenv "EZMESURE_OIDC_CLIENT_SECRET" }}
  name: '{{ getenv "EZMESURE_APPLICATION_NAME"}}'
  redirectURIs:
    - '{{ getenv "EZMESURE_PUBLIC_URL" }}/api/auth/oauth/login/callback'

connectors:
- type: mockCallback
  id: mock
  name: Mock
